const LABS=["Lab A","Lab C","Lab D","Lab LC"];
const TYPES=[["jord","Jord"],["materialer","Materialer"]];
const DESTINATIONS=["Prag","Luleå","GBA","Andet"];
const ANALYSES=["Kulbrinter","Phtalater","Florisil","HydrocarbonerNorge","Styren","Alifater","Btex","Chlorbenzener","Pah materiele","Pah sediment","Pah 17","PAH","Polære","DCM","MTBE","Pesticider","Phenol og Creosoter","PCB i jord","Freon","Glyphosat/AMPA","Flygtige syrer","Chlorparaffiner fuge","PCB fuge","Acrylamid og Glycoler","Grindstedpakken","N-methyl-2pyrrolidon","Aldehyd (Formaldehyd)","PFAS i Jord og materiale (DK)","Tørstof","Glødetab (se tørstof)","HG","ICP slam","ICP","Metaller","ICP + HG","Antimon","Total N i løv","Total N i jord og slam","Chrom VI jord til tørring 40°C","Chrom ISO","TOC – vådt (Norge)","TOC – tørt (Dk)","Cyanid","Chlorid, vandopløselig","Sulfat, vandopløselig","Fluorid, vandopløselig","Fosfortal","Ledningsevne","pH/reaktionstal","pH i Jord","Udvaskningstest","Baumann Gully","Basemætning","BD-ekstraktion","Pyrit","Citrat opløselig fosfor"];
const REASONS=["High resultat","Low resultat","Høj Terbium","Afvigelse QC","Mistanke om pipettering","Mistanke om homogenisering","Instrument check","Matrix/interferens","Efterbestilling","Ukendt"];

let state={view:"labselect",lab:"Lab A",sampleType:"jord",destination:"Prag",rows:[],error:"",connected:false};

document.addEventListener("DOMContentLoaded",async()=>{state.connected=initSupabase();render();if(state.connected)await refresh();setInterval(()=>{if(state.connected)refresh(false)},15000)});

function escapeHtml(v){return String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function labelType(t){return t==="materialer"?"Materialer":"Jord"}
function toast(m){const d=document.createElement("div");d.className="toast";d.textContent=m;document.body.appendChild(d);setTimeout(()=>d.remove(),3000)}
async function refresh(showError=true){try{state.rows=await fetchRepairs();state.error=""}catch(e){if(showError)state.error=e.message}render()}
function activeBtn(v,c){return v===c?"active":""}
function layout(content){return `<div class="app"><aside class="sidebar"><div class="logo">OMW LabRepair<small>Functional v1</small></div>
<div><div class="side-section">Indsendelse</div><button class="side-btn ${state.view==='labselect'||state.view==='labform'?'active':''}" onclick="go('labselect')"><span class="icon">L</span> Lab reparationer</button><button class="side-btn ${state.view==='sendselect'||state.view==='sendform'?'active':''}" onclick="go('sendselect')"><span class="icon">S</span> Send til</button></div>
<div><div class="side-section">Afvejning</div><button class="side-btn ${state.view==='afvjord'?'active':''}" onclick="go('afvjord')"><span class="icon">J</span> Afvejning Jord</button><button class="side-btn ${state.view==='afvmat'?'active':''}" onclick="go('afvmat')"><span class="icon">M</span> Afvejning Materialer</button></div>
<div><div class="side-section">Overblik</div><button class="side-btn ${state.view==='archive'?'active':''}" onclick="go('archive')"><span class="icon">R</span> Arkiv</button><button class="side-btn ${state.view==='dashboard'?'active':''}" onclick="go('dashboard')"><span class="icon">D</span> Dashboard</button><button class="side-btn ${state.view==='setup'?'active':''}" onclick="go('setup')"><span class="icon">⚙</span> Opsætning</button></div>
</aside><main class="main">${state.error?`<div class="error">${escapeHtml(state.error)}</div>`:""}${content}</main></div>`}
function go(v){state.view=v;render()}

function render(){let html=""; if(state.view==="setup")html=setupView(); if(state.view==="labselect")html=labSelect(); if(state.view==="labform")html=labForm(); if(state.view==="sendselect")html=sendSelect(); if(state.view==="sendform")html=sendForm(); if(state.view==="afvjord")html=afv("jord"); if(state.view==="afvmat")html=afv("materialer"); if(state.view==="archive")html=archiveView(); if(state.view==="dashboard")html=dashboardView(); document.getElementById("app").innerHTML=layout(html)}
function header(t,s){return `<div class="topbar"><div><h1>${t}</h1><div class="subtitle">${s}</div></div><div class="status"><span class="dot ${state.connected?'ok':''}"></span>${state.connected?'Forbundet':'Ikke forbundet'}</div></div>`}

function setupView(){const c=getConfig();return `${header("Opsætning","Indtast Supabase URL og Publishable key. Gemmes kun i denne browser.")}<div class="card"><label>Supabase URL<input id="url" value="${escapeHtml(c.supabaseUrl||"")}"></label><br><br><label>Publishable key<input id="key" value="${escapeHtml(c.supabaseKey||"")}"></label><div class="actions"><button class="primary" onclick="saveSetup()">Gem og test</button></div></div>`}
async function saveSetup(){saveConfig({supabaseUrl:document.getElementById("url").value.trim(),supabaseKey:document.getElementById("key").value.trim()});state.connected=initSupabase();try{await testConnection();toast("Forbindelse OK");await refresh(false);go("labselect")}catch(e){state.error=e.message;render()}}

function labSelect(){return `${header("Lab reparationer","Vælg lab og type én gang for hele sendingen.")}<div class="card"><h3>1. Vælg laboratorium</h3><div class="option-grid">${LABS.map(l=>`<button class="option ${activeBtn(l,state.lab)}" onclick="state.lab='${l}';render()">${l}</button>`).join("")}</div><h3>2. Vælg type</h3><div class="option-grid" style="grid-template-columns:repeat(2,1fr)">${TYPES.map(([v,l])=>`<button class="option ${activeBtn(v,state.sampleType)}" onclick="state.sampleType='${v}';render()">${l}</button>`).join("")}</div><div class="actions"><button class="primary" onclick="go('labform')">Fortsæt</button></div></div>`}
function dataLists(){return `<datalist id="analyses">${ANALYSES.map(a=>`<option value="${escapeHtml(a)}"></option>`).join("")}</datalist><datalist id="reasons">${REASONS.map(r=>`<option value="${escapeHtml(r)}"></option>`).join("")}</datalist>`}
function labForm(){return `${header("Lab reparationer",`${state.lab} · ${labelType(state.sampleType)}`)}${dataLists()}<div class="card"><div class="toolbar"><div><b>Afsender:</b> ${state.lab} · <span class="pill ${state.sampleType}">${labelType(state.sampleType)}</span></div><button onclick="go('labselect')">Skift lab/type</button></div><div class="table-wrap"><table class="form-table"><thead><tr><th>#</th><th>Prøve</th><th>Kasse</th><th>Analyse</th><th>Bestems</th><th>Årsag</th><th>Kommentar</th><th>1. vejedato</th><th>Haster</th></tr></thead><tbody>${Array.from({length:20},(_,i)=>`<tr><td>${i+1}</td><td><input data-row="${i}" data-f="sample"></td><td><input data-row="${i}" data-f="box"></td><td><input list="analyses" data-row="${i}" data-f="analysis"></td><td><input data-row="${i}" data-f="determinations"></td><td><input list="reasons" data-row="${i}" data-f="reason"></td><td><textarea data-row="${i}" data-f="comment"></textarea></td><td><input type="date" value="${new Date().toISOString().slice(0,10)}" data-row="${i}" data-f="first_weighing"></td><td><input type="checkbox" data-row="${i}" data-f="urgent"></td></tr>`).join("")}</tbody></table></div><div class="actions"><button class="primary" onclick="submitLab()">Send udfyldte</button></div></div>`}
async function submitLab(){const items=collect().map(r=>({request_type:"reparation",sample_type:state.sampleType,lab:state.lab,destination:null,grams:null,sample:r.sample,box:r.box,analysis:r.analysis,determinations:r.determinations,reason:r.reason,comment:r.comment,first_weighing:r.first_weighing,urgent:!!r.urgent,status:"ny",printed:false})); if(!items.length)return toast("Ingen komplette rækker."); await insertRows(items); toast(`${items.length} sendt`); await refresh(false); go(state.sampleType==="jord"?"afvjord":"afvmat")}
function collect(){const rows={};document.querySelectorAll("[data-row]").forEach(el=>{const r=el.dataset.row,f=el.dataset.f;rows[r]=rows[r]||{};rows[r][f]=el.type==="checkbox"?el.checked:el.value.trim()});return Object.values(rows).filter(r=>r.sample&&r.box&&r.first_weighing)}

function sendSelect(){return `${header("Send til","Vælg type og destination én gang for hele sendingen.")}<div class="card"><h3>1. Vælg type</h3><div class="option-grid" style="grid-template-columns:repeat(2,1fr)">${TYPES.map(([v,l])=>`<button class="option ${activeBtn(v,state.sampleType)}" onclick="state.sampleType='${v}';render()">${l}</button>`).join("")}</div><h3>2. Vælg destination</h3><div class="option-grid">${DESTINATIONS.map(d=>`<button class="option ${activeBtn(d,state.destination)}" onclick="state.destination='${d}';render()">${d}</button>`).join("")}</div><div class="actions"><button class="primary" onclick="go('sendform')">Fortsæt</button></div></div>`}
function sendForm(){return `${header("Send til",`${labelType(state.sampleType)} · ${state.destination}`)}<div class="card"><div class="toolbar"><div><b>Destination:</b> ${state.destination} · <span class="pill ${state.sampleType}">${labelType(state.sampleType)}</span></div><button onclick="go('sendselect')">Skift type/destination</button></div><table><thead><tr><th>#</th><th>Prøve</th><th>Kasse</th><th>Gram</th><th>1. vejedato</th></tr></thead><tbody>${Array.from({length:20},(_,i)=>`<tr><td>${i+1}</td><td><input data-row="${i}" data-f="sample"></td><td><input data-row="${i}" data-f="box"></td><td><input data-row="${i}" data-f="grams" type="number" step="0.01"></td><td><input type="date" value="${new Date().toISOString().slice(0,10)}" data-row="${i}" data-f="first_weighing"></td></tr>`).join("")}</tbody></table><div class="actions"><button class="primary" onclick="submitSendTil()">Send udfyldte</button></div></div>`}
async function submitSendTil(){const items=collect().map(r=>({request_type:"send_til",sample_type:state.sampleType,lab:"Send til",destination:state.destination,grams:r.grams?Number(r.grams):null,sample:r.sample,box:r.box,analysis:null,determinations:null,reason:null,comment:null,first_weighing:r.first_weighing,urgent:false,status:"ny",printed:false})); if(!items.length)return toast("Ingen komplette rækker."); await insertRows(items); toast(`${items.length} sendt`); await refresh(false); go(state.sampleType==="jord"?"afvjord":"afvmat")}

function afv(type){const rep=activeRows().filter(r=>r.sample_type===type&&r.request_type==="reparation");const send=activeRows().filter(r=>r.sample_type===type&&r.request_type==="send_til");return `${header("Afvejning "+labelType(type),`Viser kun ${labelType(type).toLowerCase()}.`)}<div class="card"><div class="toolbar"><b>Reparationer (${rep.length})</b><div><button class="primary" onclick='printAndMark(${JSON.stringify(rep.map(x=>x.id))},"Reparationer")'>Print A4</button><button class="green" onclick='archive(${JSON.stringify(rep.map(x=>x.id))})'>Arkivér</button></div></div>${tableRep(rep)}</div><div class="card"><div class="toolbar"><b>Send til (${send.length})</b><div><button class="primary" onclick='printAndMark(${JSON.stringify(send.map(x=>x.id))},"Send til")'>Print A4</button><button class="green" onclick='archive(${JSON.stringify(send.map(x=>x.id))})'>Arkivér</button></div></div>${tableSend(send)}</div>`}
function activeRows(){return state.rows.filter(r=>(r.status||"ny")==="ny")}
function tableRep(rows){if(!rows.length)return "<p class='subtitle'>Ingen data</p>";return `<table><thead><tr><th>Lab</th><th>Prøve</th><th>Kasse</th><th>Analyse</th><th>Bestems</th><th>Årsag</th><th>Haster</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.lab}</td><td><b>${r.sample}</b></td><td>${r.box||""}</td><td>${r.analysis||""}</td><td>${r.determinations||""}</td><td>${r.reason||""}</td><td>${r.urgent?"<span class='pill red'>Haster</span>":""}</td></tr>`).join("")}</tbody></table>`}
function tableSend(rows){if(!rows.length)return "<p class='subtitle'>Ingen data</p>";return `<table><thead><tr><th>Destination</th><th>Prøve</th><th>Kasse</th><th>Gram</th><th>1. vejedato</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.destination||""}</td><td><b>${r.sample}</b></td><td>${r.box||""}</td><td>${r.grams||""} g</td><td>${r.first_weighing||""}</td></tr>`).join("")}</tbody></table>`}
async function printAndMark(ids,title){const rows=state.rows.filter(r=>ids.includes(r.id));printRows(rows,title);await updateRows(ids,{printed:true,printed_at:new Date().toISOString(),printed_by:"Afvejning"});await refresh(false)}
async function archive(ids){if(!ids.length)return toast("Ingen rækker.");await updateRows(ids,{status:"arkiv",archive_date:new Date().toISOString(),archive_by:"Afvejning"});toast("Flyttet til arkiv");await refresh(false)}
function archiveView(){const rows=state.rows.filter(r=>(r.status||"ny")==="arkiv");return `${header("Arkiv","Ét fælles arkiv.")}<div class="card">${tableArchive(rows)}</div>`}
function tableArchive(rows){if(!rows.length)return "<p class='subtitle'>Ingen arkivdata</p>";return `<table><thead><tr><th>Type</th><th>Afsender</th><th>Prøve</th><th>Analyse/Destination</th><th>Arkiveret</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${labelType(r.sample_type)}</td><td>${r.lab}</td><td>${r.sample}</td><td>${r.analysis||r.destination||""}</td><td>${r.archive_date||""}</td></tr>`).join("")}</tbody></table>`}
function dashboardView(){const active=activeRows();return `${header("Dashboard","Overblik.")}<div class="cards"><div class="card"><div class="metric">${active.length}</div><div class="label">Nye total</div></div><div class="card"><div class="metric">${active.filter(r=>r.sample_type==="jord").length}</div><div class="label">Jord</div></div><div class="card"><div class="metric">${active.filter(r=>r.sample_type==="materialer").length}</div><div class="label">Materialer</div></div><div class="card"><div class="metric">${active.filter(r=>r.urgent).length}</div><div class="label">Haster</div></div></div>`}
